# Generated by Django 4.1.11 on 2023-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='demo',
            field=models.CharField(default='*', max_length=10),
        ),
    ]
